### ISSUE TITLE
An easy fix

### ISSUE THREAD

**Issue by yaoyongxin** [rigetti/forest-tutorials#1]
In forest-tutorials/notebooks/VariationalQuantumEigensolver.ipynb cell 2,  I think the line

qc = get_qc("2q-noisy-qvm")

should be replaced by 

qc = get_qc("2q-qvm")

Otherwise, qc is a simple duplicate of qc_noise.

**Comment by appleby** [comment]
Hello! Thanks for reporting this. Sorry for the delay; I was not receiving notifications for this repo.

That does indeed look like a typo. I will push a fix as soon as I get commit permissions for this repo.
