### ISSUE TITLE
Code doesn't work when modifying the qc to Aspen-4-2Q-A-noisy-qvm.

### ISSUE THREAD

**Issue by yaoyongxin** [rigetti/forest-tutorials#2]
I tried modifying the qc in https://github.com/rigetti/forest-tutorials/blob/master/notebooks/VariationalQuantumEigensolver.ipynb, by replacing

qc = get_qc("2q-noisy-qvm")
qc_noisy = get_qc("2q-noisy-qvm")

with 

qc = get_qc("Aspen-4-2Q-A-qvm")
qc_noisy = get_qc("Aspen-4-2Q-A-noisy-qvm")

.
The code crashes at step of 

results.append(qc.experiment(h2_vqe, memory_map={"theta": [theta]}))

with error message:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-31-be4ef6fe2f77> in <module>
      1 results = []
      2 for theta in tqdm(thetas):
----> 3     results.append(qc.experiment(h2_vqe, memory_map={"theta": [theta]}))

~/.virtualenvs/venv/lib/python3.6/site-packages/pyquil/api/_error_reporting.py in wrapper(*args, **kwargs)
    249             global_error_context.log[key] = pre_entry
    250 
--> 251         val = func(*args, **kwargs)
    252 
    253         # poke the return value of that call in

~/.virtualenvs/venv/lib/python3.6/site-packages/pyquil/api/_quantum_computer.py in experiment(self, experiment, memory_map)
    234             for merged_memory_map in merged_memory_maps:
    235                 final_memory_map = {**memory_map, **merged_memory_map}
--> 236                 bitstrings = self.run(executable, memory_map=final_memory_map)
    237 
    238                 if "symmetrization" in final_memory_map:

~/.virtualenvs/venv/lib/python3.6/site-packages/pyquil/api/_error_reporting.py in wrapper(*args, **kwargs)
    249             global_error_context.log[key] = pre_entry
    250 
--> 251         val = func(*args, **kwargs)
    252 
    253         # poke the return value of that call in

~/.virtualenvs/venv/lib/python3.6/site-packages/pyquil/api/_quantum_computer.py in run(self, executable, memory_map)
    131         :return: A numpy array of shape (trials, len(ro-register)) that contains 0s and 1s.
    132         """
--> 133         self.qam.load(executable)
    134         if memory_map:
    135             for region_name, values_list in memory_map.items():

~/.virtualenvs/venv/lib/python3.6/site-packages/pyquil/api/_error_reporting.py in wrapper(*args, **kwargs)
    249             global_error_context.log[key] = pre_entry
    250 
--> 251         val = func(*args, **kwargs)
    252 
    253         # poke the return value of that call in

~/.virtualenvs/venv/lib/python3.6/site-packages/pyquil/api/_qvm.py in load(self, executable)
    522             else:
    523                 raise TypeError(
--> 524                     "`executable` argument must be a `PyQuilExecutableResponse`. Make "
    525                     "sure you have explicitly compiled your program via `qc.compile` "
    526                     "or `qc.compiler.native_quil_to_executable(...)` for more "

TypeError: `executable` argument must be a `PyQuilExecutableResponse`. Make sure you have explicitly compiled your program via `qc.compile` or `qc.compiler.native_quil_to_executable(...)` for more fine-grained control. This explicit step is required for running on a QPU.

I think there is a bug in _quantum_computer.py. A simple fix, which seems too simple for me, is to add a line

         self.qam._executable = executable

before 

         return results

in the def experiment block. I would appreciate a conformation if it is a correct fix. Thanks!

**Comment by appleby** [comment]
Thanks for reporting this. The fix is a little more involved and has to do with the interplay between `QuantumComuter.experiment` re-using loaded executables to avoid recompilation, plus the fact that `QVM`s based on real devices require executables to be compiled in order to load them, but actually save the uncompiled `Program` in `self._executable`.

This is actually a pyQuil bug, so I will submit a PR there to address it.

**Comment by yaoyongxin** [comment]
Hi, just would like to know whether there is some estimation when the issue will be resolved. As of now, I test the tutorial  https://github.com/rigetti/forest-tutorials/blob/master/notebooks/VariationalQuantumEigensolver.ipynb using Aspen-4-2Q-G-qvm, and it still does not work. I would think it is a very important issue, as any serious work using the devices would encounter that. Many thanks for your efforts!

**Comment by notmgsk** [comment]
Hi @yaoyongxin. A fix was merged into pyQuil. It'll be included in the next pyQuil release (coming up this week).
